name: RestartAnnouncer
version: '${project.version}'
main: com.restartannouncer.RestartAnnouncerPlugin
api-version: '1.20'
description: A highly configurable restart announcement plugin with in-game configuration
authors: [MightyFinger77]

commands:
  announcer:
    description: Main command for RestartAnnouncer plugin
    usage: /<command> [subcommand] [args...]
    aliases: [ra, restartannouncer]
    permission: announcer.use

permissions:
  announcer.use:
    description: Allows basic usage of the announcer command
    default: true
  announcer.start:
    description: Allows starting restart countdowns
    default: op
  announcer.stop:
    description: Allows stopping restart countdowns
    default: op
  announcer.status:
    description: Allows checking restart status and time remaining
    default: op
  announcer.reload:
    description: Allows reloading the plugin configuration
    default: op
  announcer.update:
    description: Allows checking for plugin updates
    default: op
  announcer.admin:
    description: Allows full administrative control over the plugin
    default: op
    children:
      announcer.use: true
      announcer.start: true
      announcer.stop: true
      announcer.status: true
      announcer.reload: true
      announcer.update: true 